const ADD_TO_DO = 'ADD_TO_DO';
const REMOVE_TO_DO = 'REMOVE_TO_DO';
const FILTER_CHANGE = 'FILTER_CHANGE';
const STATUS_CHANGE = 'STATUS_CHANGE';
const OPEN_MODAL = 'OPEN_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';

export {
    ADD_TO_DO,
    CLOSE_MODAL,
    FILTER_CHANGE,
    OPEN_MODAL,
    REMOVE_TO_DO,
    STATUS_CHANGE,
}